package net.ivoireautoservice.ias_manager.enums;

public enum PhotoMissionTypeEnum {
	PHOTO_AVANT_GAUCHE,
	PHOTO_AVANT_DROITE,
	PHOTO_ARRIERE_GAUCHE,
	PHOTO_ARRIERE_DROITE,
	SIGNATURE_CHAUFFEUR,
	SIGNATURE_IAS,
	PHOTO_FIN_AVANT_GAUCHE,
	PHOTO_FIN_AVANT_DROITE,
	PHOTO_FIN_ARRIERE_GAUCHE,
	PHOTO_FIN_ARRIERE_DROITE,
	SIGNATURE_FIN_CHAUFFEUR,
	SIGNATURE_FIN_IAS
}
