spring.application.name=ias_manager
debug=true
ias.security.secret: 9b1c9c5b8d4f6e7a8b9c1d2e3f4a5b6c9b1c9c5b8d4f6e7a
ias.security.expiration: 3600000
ias.security.issuer: ias-manager-api

spring.datasource.url=jdbc:mariadb://192.168.2.22:3306/ias_manager
spring.datasource.username=root
spring.datasource.password=Azerty@2023
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
