ALTER TABLE VEHICULES ADD COLUMN IF NOT EXISTS fin_validite_patente DATE;
ALTER TABLE VEHICULES ADD COLUMN IF NOT EXISTS fin_validite_carte_stationnement DATE;
ALTER TABLE VEHICULES ADD COLUMN IF NOT EXISTS fin_validite_carte_transport DATE;
