-- =============================================================================
-- Migration manuelle : réinitialisation des permissions des rôles système.
--
-- Le catalogue PermissionEnum a été entièrement réécrit (ex. FACTURE_* ->
-- FACTURE_CLIENT_*/FACTURE_FOURNISSEUR_*, COMPTE_* -> TRESORERIE_*,
-- MISSION_CANCEL -> MISSION_ANNULER, tous les *_MANAGE -> CRUD, ...). La table
-- role_permissions contenait encore l'ancien vocabulaire, ce qui faisait échouer
-- le mapping @Enumerated(STRING) au démarrage :
--   java.lang.IllegalArgumentException: No enum constant ...PermissionEnum.BON_COMMANDE_MANAGE
--
-- Ce script purge toutes les permissions stockées puis ré-applique les valeurs
-- par défaut définies dans RbacSeeder.permissionsParDefaut(...). Les affectations
-- utilisateur<->rôle et groupe<->rôle sont préservées (seul role_permissions est
-- touché). Idempotent. ADMIN est de toute façon resynchronisé sur l'ensemble
-- complet par RbacSeeder au démarrage ; il est inclus ici pour que la base reste
-- cohérente même si le seeder est désactivé.
-- =============================================================================

-- 0a) La colonne avait été créée par Hibernate en ENUM natif MySQL figé sur
--     l'ancien vocabulaire. ddl-auto=update ne modifie jamais la liste de valeurs
--     d'un ENUM existant : on la convertit en VARCHAR(255) (conforme au schéma
--     documenté dans 2026-06-11_rbac.sql) pour qu'elle accepte le vocabulaire
--     courant et toute permission future.
ALTER TABLE role_permissions MODIFY permission VARCHAR(255) NOT NULL;

-- 0b) Table de mappage rôle -> permission (vocabulaire courant uniquement).
DELETE FROM role_permissions;

-- 1) ADMIN : toutes les permissions.
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
JOIN (
    SELECT 'DASHBOARD_READ' AS permission
    UNION ALL SELECT 'VEHICULE_READ'   UNION ALL SELECT 'VEHICULE_CREATE'
    UNION ALL SELECT 'VEHICULE_UPDATE' UNION ALL SELECT 'VEHICULE_DELETE'
    UNION ALL SELECT 'MISSION_READ'    UNION ALL SELECT 'MISSION_CREATE'
    UNION ALL SELECT 'MISSION_UPDATE'  UNION ALL SELECT 'MISSION_ANNULER'
    UNION ALL SELECT 'INTERVENTION_READ'   UNION ALL SELECT 'INTERVENTION_CREATE'
    UNION ALL SELECT 'INTERVENTION_UPDATE' UNION ALL SELECT 'INTERVENTION_DELETE'
    UNION ALL SELECT 'EMPLOYE_READ'   UNION ALL SELECT 'EMPLOYE_CREATE'
    UNION ALL SELECT 'EMPLOYE_UPDATE' UNION ALL SELECT 'EMPLOYE_DELETE'
    UNION ALL SELECT 'CHAUFFEUR_READ'   UNION ALL SELECT 'CHAUFFEUR_CREATE'
    UNION ALL SELECT 'CHAUFFEUR_UPDATE' UNION ALL SELECT 'CHAUFFEUR_DELETE'
    UNION ALL SELECT 'PRODUIT_READ'   UNION ALL SELECT 'PRODUIT_CREATE'
    UNION ALL SELECT 'PRODUIT_UPDATE' UNION ALL SELECT 'PRODUIT_DELETE'
    UNION ALL SELECT 'BON_COMMANDE_READ'   UNION ALL SELECT 'BON_COMMANDE_CREATE'
    UNION ALL SELECT 'BON_COMMANDE_UPDATE' UNION ALL SELECT 'BON_COMMANDE_DELETE'
    UNION ALL SELECT 'APPRO_READ'   UNION ALL SELECT 'APPRO_CREATE'
    UNION ALL SELECT 'APPRO_UPDATE' UNION ALL SELECT 'APPRO_DELETE'
    UNION ALL SELECT 'LIVRAISON_CLIENT_READ'   UNION ALL SELECT 'LIVRAISON_CLIENT_CREATE'
    UNION ALL SELECT 'LIVRAISON_CLIENT_UPDATE' UNION ALL SELECT 'LIVRAISON_CLIENT_DELETE'
    UNION ALL SELECT 'TRESORERIE_READ'      UNION ALL SELECT 'TRESORERIE_CREATE'
    UNION ALL SELECT 'TRESORERIE_UPDATE'    UNION ALL SELECT 'TRESORERIE_APPROUVER'
    UNION ALL SELECT 'TRESORERIE_SOLDER'
    UNION ALL SELECT 'FACTURE_FOURNISSEUR_READ'    UNION ALL SELECT 'FACTURE_FOURNISSEUR_CREATE'
    UNION ALL SELECT 'FACTURE_FOURNISSEUR_VALIDER' UNION ALL SELECT 'FACTURE_FOURNISSEUR_DELETE'
    UNION ALL SELECT 'FACTURE_CLIENT_READ'    UNION ALL SELECT 'FACTURE_CLIENT_CREATE'
    UNION ALL SELECT 'FACTURE_CLIENT_VALIDER' UNION ALL SELECT 'FACTURE_CLIENT_DELETE'
    UNION ALL SELECT 'RAPPORT_READ'
    UNION ALL SELECT 'PARTENAIRE_READ'   UNION ALL SELECT 'PARTENAIRE_CREATE'
    UNION ALL SELECT 'PARTENAIRE_UPDATE' UNION ALL SELECT 'PARTENAIRE_DELETE'
    UNION ALL SELECT 'PARAMETRE_READ'   UNION ALL SELECT 'PARAMETRE_MANAGE'
    UNION ALL SELECT 'UTILISATEUR_READ' UNION ALL SELECT 'UTILISATEUR_MANAGE'
    UNION ALL SELECT 'ROLE_MANAGE'      UNION ALL SELECT 'GROUPE_MANAGE'
) p
WHERE r.nom = 'ADMIN';

-- 2) LOGISTIQUE
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
JOIN (
    SELECT 'DASHBOARD_READ' AS permission
    UNION ALL SELECT 'VEHICULE_READ'   UNION ALL SELECT 'VEHICULE_CREATE'
    UNION ALL SELECT 'VEHICULE_UPDATE' UNION ALL SELECT 'VEHICULE_DELETE'
    UNION ALL SELECT 'MISSION_READ'    UNION ALL SELECT 'MISSION_CREATE'
    UNION ALL SELECT 'MISSION_UPDATE'  UNION ALL SELECT 'MISSION_ANNULER'
    UNION ALL SELECT 'INTERVENTION_READ'   UNION ALL SELECT 'INTERVENTION_CREATE'
    UNION ALL SELECT 'INTERVENTION_UPDATE' UNION ALL SELECT 'INTERVENTION_DELETE'
    UNION ALL SELECT 'CHAUFFEUR_READ'
    UNION ALL SELECT 'LIVRAISON_CLIENT_READ'   UNION ALL SELECT 'LIVRAISON_CLIENT_CREATE'
    UNION ALL SELECT 'LIVRAISON_CLIENT_UPDATE' UNION ALL SELECT 'LIVRAISON_CLIENT_DELETE'
) p
WHERE r.nom = 'LOGISTIQUE';

-- 3) COMMERCIAL
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
JOIN (
    SELECT 'DASHBOARD_READ' AS permission
    UNION ALL SELECT 'FACTURE_CLIENT_READ'   UNION ALL SELECT 'FACTURE_CLIENT_CREATE'
    UNION ALL SELECT 'FACTURE_CLIENT_VALIDER'
    UNION ALL SELECT 'PARTENAIRE_READ'   UNION ALL SELECT 'PARTENAIRE_CREATE'
    UNION ALL SELECT 'PARTENAIRE_UPDATE'
    UNION ALL SELECT 'MISSION_READ'
    UNION ALL SELECT 'LIVRAISON_CLIENT_READ' UNION ALL SELECT 'LIVRAISON_CLIENT_CREATE'
    UNION ALL SELECT 'RAPPORT_READ'
) p
WHERE r.nom = 'COMMERCIAL';

-- 4) RECOUVREMENT
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
JOIN (
    SELECT 'DASHBOARD_READ' AS permission
    UNION ALL SELECT 'FACTURE_CLIENT_READ' UNION ALL SELECT 'FACTURE_CLIENT_VALIDER'
    UNION ALL SELECT 'FACTURE_FOURNISSEUR_READ' UNION ALL SELECT 'FACTURE_FOURNISSEUR_VALIDER'
    UNION ALL SELECT 'TRESORERIE_READ'   UNION ALL SELECT 'TRESORERIE_CREATE'
    UNION ALL SELECT 'TRESORERIE_UPDATE' UNION ALL SELECT 'TRESORERIE_APPROUVER'
    UNION ALL SELECT 'TRESORERIE_SOLDER'
    UNION ALL SELECT 'RAPPORT_READ'
) p
WHERE r.nom = 'RECOUVREMENT';

-- 5) RH
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
JOIN (
    SELECT 'DASHBOARD_READ' AS permission
    UNION ALL SELECT 'EMPLOYE_READ'   UNION ALL SELECT 'EMPLOYE_CREATE'
    UNION ALL SELECT 'EMPLOYE_UPDATE' UNION ALL SELECT 'EMPLOYE_DELETE'
    UNION ALL SELECT 'CHAUFFEUR_READ'   UNION ALL SELECT 'CHAUFFEUR_CREATE'
    UNION ALL SELECT 'CHAUFFEUR_UPDATE' UNION ALL SELECT 'CHAUFFEUR_DELETE'
) p
WHERE r.nom = 'RH';

-- 6) ACHAT
INSERT INTO role_permissions (role_id, permission)
SELECT r.id, p.permission FROM roles r
JOIN (
    SELECT 'DASHBOARD_READ' AS permission
    UNION ALL SELECT 'BON_COMMANDE_READ'   UNION ALL SELECT 'BON_COMMANDE_CREATE'
    UNION ALL SELECT 'BON_COMMANDE_UPDATE' UNION ALL SELECT 'BON_COMMANDE_DELETE'
    UNION ALL SELECT 'APPRO_READ'   UNION ALL SELECT 'APPRO_CREATE'
    UNION ALL SELECT 'APPRO_UPDATE' UNION ALL SELECT 'APPRO_DELETE'
    UNION ALL SELECT 'PRODUIT_READ'   UNION ALL SELECT 'PRODUIT_CREATE'
    UNION ALL SELECT 'PRODUIT_UPDATE' UNION ALL SELECT 'PRODUIT_DELETE'
    UNION ALL SELECT 'FACTURE_FOURNISSEUR_READ' UNION ALL SELECT 'FACTURE_FOURNISSEUR_CREATE'
    UNION ALL SELECT 'PARTENAIRE_READ'
) p
WHERE r.nom = 'ACHAT';
